import java.util.Scanner;

public class OnlineResumeSystem {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("User Profile:");
        System.out.print("Enter Full Name: ");
        String fullName = scanner.nextLine();
        System.out.print("Enter Contact Number: ");
        String contactNumber = scanner.nextLine();
        System.out.print("Enter Email Address: ");
        String emailAddress = scanner.nextLine();
        System.out.print("Enter Address: ");
        String address = scanner.nextLine();
        System.out.print("Enter Date of Birth (YYYY-MM-DD): ");
        String dateOfBirth = scanner.nextLine();
        System.out.print("Enter Gender: ");
        String gender = scanner.nextLine();
        System.out.print("Enter Nationality: ");
        String nationality = scanner.nextLine();
        System.out.print("Enter LinkedIn Profile URL: ");
        String linkedInProfileURL = scanner.nextLine();
        System.out.print("Enter GitHub Profile URL: ");
        String gitHubProfileURL = scanner.nextLine();
        System.out.print("Enter Profile Image Path: ");
        String profileImagePath = scanner.nextLine();
        // Education Details
        System.out.println("\nEducation Details:");
        System.out.print("Enter Degree Name: ");
        String degreeName = scanner.nextLine();
        System.out.print("Enter University Name: ");
        String universityName = scanner.nextLine();
        System.out.print("Enter Major/Field of Study: ");
        String fieldOfStudy = scanner.nextLine();
        System.out.print("Enter Graduation Year: ");
        int graduationYear = scanner.nextInt();
        System.out.print("Enter GPA: ");
        double gpa = scanner.nextDouble();
        scanner.nextLine(); 
        System.out.print("Enter Honors/Awards: ");
        String honorsAwards = scanner.nextLine();
        System.out.print("Enter Revelent courses: ");
        String revelentcourses = scanner.nextLine();
        System.out.print("Enter Thesis Title: ");
        String thesistitle = scanner.nextLine();
        System.out.print("Enter Educational Institution Location: ");
        String educationalinstitutionlocation = scanner.nextLine();
        System.out.print("Enter Extracurricular Activities : ");
        String extracurricularactivities  = scanner.nextLine();
        // Work Experience
        System.out.println("\nWork Experience:");
        System.out.print("Enter Company Name: ");
        String companyName = scanner.nextLine();
        System.out.print("Enter Job Title: ");
        String jobTitle = scanner.nextLine();
        System.out.print("Enter Employment Period (YYYY-MM-DD to YYYY-MM-DD): ");
        String employmentPeriod = scanner.nextLine();
        System.out.print("Enter Job Description: ");
        String jobDescription = scanner.nextLine();
        System.out.print("Enter Achievements: ");
        String achievements = scanner.nextLine();
        System.out.print("Enter Responsibilities ");
        String responsibilities = scanner.nextLine();
        System.out.print("Enter Work Location ");
        String worklocation = scanner.nextLine();
        System.out.print("Enter Supervisor Name ");
        String supervisorname  = scanner.nextLine();
        System.out.print("Enter Contact Number of Supervisor ");
        String contactnumberofsupervisor  = scanner.nextLine();
        System.out.print("Enter Email of Supervisor ");
        String emailofsupervisor  = scanner.nextLine();
        System.out.println("\nSkills:");
        System.out.print("Enter Programming Languages: ");
        String programminglanguages = scanner.nextLine();
        System.out.print("Enter Technical Skills : ");
        String technicalskills  = scanner.nextLine();
        System.out.print("Enter Soft Skills: ");
        String softskills  = scanner.nextLine();
        System.out.print("Enter Certifications: ");
        String certifications  = scanner.nextLine();
        System.out.print("Enter Language Proficiency : ");
        String languageproficiency = scanner.nextLine();
        System.out.print("Enter Project Management: ");
        String projectmanagement = scanner.nextLine();
        System.out.print("Enter Industry Knowledge: ");
        String industryknowledge = scanner.nextLine();
        System.out.print("Enter Tools and Technologies: ");
        String toolsandtechnologies = scanner.nextLine();
        System.out.print("Enter Collaboration Tools: ");
        String collaborationtools = scanner.nextLine();
        System.out.print("Enter Problem Solving: ");
        String problemsolving = scanner.nextLine();
        System.out.println("\nProjects:");
        System.out.print("Enter Project Title: ");
        String projectTitle = scanner.nextLine();
        System.out.print("Enter Project Description: ");
        String projectDescription = scanner.nextLine();
        System.out.print("Enter Project Duration (YYYY-MM-DD to YYYY-MM-DD): ");
        String projectDuration = scanner.nextLine();
        System.out.print("Enter Team Size: ");
        int teamSize = scanner.nextInt();
        scanner.nextLine(); 
        System.out.print("Enter Your Role in Project: ");
        String roleInProject = scanner.nextLine();
        System.out.print("Enter Technologies Used: ");
        String technologiesUsed = scanner.nextLine();
        System.out.print("Enter Project Link: ");
        String projectLink = scanner.nextLine();
        System.out.print("Enter Project Outcome: ");
        String projectOutcome = scanner.nextLine();
        System.out.print("Enter Challenges Faced: ");
        String challengesFaced = scanner.nextLine();
        System.out.print("Enter Lessons Learned: ");
        String lessonsLearned = scanner.nextLine();
        // Certifications
        System.out.println("\nCertifications:");
        System.out.print("Enter Certification Name: ");
        String certificationName = scanner.nextLine();
        System.out.print("Enter Certification Authority: ");
        String certificationAuthority = scanner.nextLine();
        System.out.print("Enter Date Obtained (YYYY-MM-DD): ");
        String dateObtained = scanner.nextLine();
        System.out.print("Enter Certification URL: ");
        String certificationURL = scanner.nextLine();
        System.out.print("Enter Validity Period (YYYY-MM-DD): ");
        String validityPeriod = scanner.nextLine();
        System.out.print("Enter Credential ID: ");
        String credentialID = scanner.nextLine();
        System.out.print("Enter Additional Information: ");
        String additionalInformation = scanner.nextLine();
        System.out.print("Enter Renewal Requirements: ");
        String renewalRequirements = scanner.nextLine();
        System.out.print("Enter Renewal Deadline (YYYY-MM-DD): ");
        String renewalDeadline = scanner.nextLine();
        System.out.print("Enter Renewal Status (true/false): ");
        boolean renewalStatus = scanner.nextBoolean();
        scanner.nextLine(); 
        // Languages
        System.out.println("\nLanguages:");
        System.out.print("Enter Language Name: ");
        String languageName = scanner.nextLine();
        System.out.print("Enter Proficiency Level: ");
        String proficiencyLevel = scanner.nextLine();
        System.out.print("Enter Writing Proficiency: ");
        String writingProficiency = scanner.nextLine();
        System.out.print("Enter Speaking Proficiency: ");
        String speakingProficiency = scanner.nextLine();
        System.out.print("Enter Reading Proficiency: ");
        String readingProficiency = scanner.nextLine();
        System.out.print("Enter Listening Proficiency: ");
        String listeningProficiency = scanner.nextLine();
        System.out.print("Enter Certification in Language (true/false): ");
        boolean languageCertification = scanner.nextBoolean();
        scanner.nextLine(); 
        System.out.print("Enter Certification Authority: ");
        String languageCertificationAuthority = scanner.nextLine();
        System.out.print("Enter Certification Date (YYYY-MM-DD): ");
        String languageCertificationDate = scanner.nextLine();
        System.out.print("Enter Certification Level: ");
        String languageCertificationLevel = scanner.nextLine();
        // Hobbies and Interests
        System.out.println("\nHobbies and Interests:");
        System.out.print("Enter Hobby/Interest Name: ");
        String hobbyName = scanner.nextLine();
        System.out.print("Enter Description: ");
        String hobbyDescription = scanner.nextLine();
        System.out.print("Enter Skill Level: ");
        String skillLevel = scanner.nextLine();
        System.out.print("Enter Time Spent Weekly: ");
        int timeSpentWeekly = scanner.nextInt();
        scanner.nextLine(); 
        System.out.print("Enter Participation in Groups/Clubs: ");
        String participationInGroups = scanner.nextLine();
        System.out.print("Enter Achievements in Hobby/Interest: ");
        String hobbyAchievements = scanner.nextLine();
        System.out.print("Enter Related Certifications (true/false): ");
        boolean hobbyCertification = scanner.nextBoolean();
        scanner.nextLine(); 
        System.out.print("Enter Certification Authority: ");
        String hobbyCertificationAuthority = scanner.nextLine();
        System.out.print("Enter Certification Date (YYYY-MM-DD): ");
        String hobbyCertificationDate = scanner.nextLine();
        System.out.print("Enter Certification Level: ");
        String hobbyCertificationLevel = scanner.nextLine();
        // References
        System.out.println("\nReferences:");
        System.out.print("Enter Reference Name: ");
        String referenceName = scanner.nextLine();
        System.out.print("Enter Relationship: ");
        String relationship = scanner.nextLine();
        System.out.print("Enter Contact Number: ");
        String referenceContactNumber = scanner.nextLine();
        System.out.print("Enter Email Address: ");
        String referenceEmailAddress = scanner.nextLine();
        System.out.print("Enter Company Name: ");
        String referenceCompanyName = scanner.nextLine();
        System.out.print("Enter Position in Company: ");
        String referencePosition = scanner.nextLine();
        System.out.print("Enter How You Know the Reference: ");
        String howYouKnowReference = scanner.nextLine();
        System.out.print("Enter Years Known: ");
        int yearsKnown = scanner.nextInt();
        // Personal Statement
        System.out.println("\nPersonal Statement:");
        System.out.print("Enter Introduction: ");
        String introduction = scanner.nextLine();
        System.out.print("Enter Career Objective: ");
        String careerObjective = scanner.nextLine();
        System.out.print("Enter Strengths: ");
        String strengths = scanner.nextLine();
        System.out.print("Enter Weaknesses: ");
        String weaknesses = scanner.nextLine();
        System.out.print("Enter Professional Achievements: ");
        String professionalAchievements = scanner.nextLine();
        System.out.print("Enter Career Aspirations: ");
        String careerAspirations = scanner.nextLine();
        System.out.print("Enter Work Philosophy: ");
        String workPhilosophy = scanner.nextLine();
        System.out.print("Enter Motivation for Career Change: ");
        String motivationForCareerChange = scanner.nextLine();
        System.out.print("Enter Long-term Goals: ");
        String longTermGoals = scanner.nextLine();
        System.out.print("Enter Short-term Goals: ");
        String shortTermGoals = scanner.nextLine();
        // Display 
        System.out.println("\nUser Profile:");
        System.out.println("Full Name: " + fullName);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Email Address: " + emailAddress);
        System.out.println("Address: " + address);
        System.out.println("Date of Birth: " + dateOfBirth);
        System.out.println("Gender: " + gender);
        System.out.println("Nationality: " + nationality);
        System.out.println("LinkedIn Profile URL: " + linkedInProfileURL);
        System.out.println("GitHub Profile URL: " + gitHubProfileURL);
        System.out.println("Profile Image Path: " + profileImagePath);
        System.out.println("\nEducation Details:");
System.out.println("Degree Name: " + degreeName);
System.out.println("University Name: " + universityName);
System.out.println("Major/Field of Study: " + fieldOfStudy);
System.out.println("Graduation Year: " + graduationYear);
System.out.println("GPA: " + gpa);
System.out.println("Honors/Awards: " + honorsAwards);
System.out.println("Relevant Courses: " + revelentcourses);
System.out.println("Thesis Title: " + thesistitle);
System.out.println("Educational Institution Location: " + educationalinstitutionlocation);
System.out.println("Extracurricular Activities: " + extracurricularactivities);

System.out.println("\nWork Experience:");
System.out.println("Company Name: " + companyName);
System.out.println("Job Title: " + jobTitle);
System.out.println("Employment Period: " + employmentPeriod);
System.out.println("Job Description: " + jobDescription);
System.out.println("Achievements: " + achievements);
System.out.println("Responsibilities: " + responsibilities);
System.out.println("Work Location: " + worklocation);
System.out.println("Supervisor Name: " + supervisorname);
System.out.println("Contact Number of Supervisor: " + contactnumberofsupervisor);
System.out.println("Email of Supervisor: " + emailofsupervisor);

        System.out.println("\nSkills:");
        System.out.println("Programming Languages: " + programminglanguages);
        System.out.println("Technical Skills: " + technicalskills);
        System.out.println("Soft Skills: " + softskills);
        System.out.println("Certifications: " + certifications);
        System.out.println("Language Proficiency: " + languageproficiency);
        System.out.println("Tools and Technologies: " + toolsandtechnologies);
        System.out.println("Industry Knowledge: " + industryknowledge);
        System.out.println("Project Management: " + projectmanagement);
        System.out.println("Collaboration Tools: " + collaborationtools);
        System.out.println("Problem Solving: " + problemsolving);

        System.out.println("\nProjects:");
        System.out.println("Project Title: " + projectTitle);
        System.out.println("Project Description: " + projectDescription);
        System.out.println("Project Duration: " + projectDuration);
        System.out.println("Team Size: " + teamSize);
        System.out.println("Role in Project: " + roleInProject);
        System.out.println("Technologies Used: " + technologiesUsed);
        System.out.println("Project Link: " + projectLink);
        System.out.println("Project Outcome: " + projectOutcome);
        System.out.println("Challenges Faced: " + challengesFaced);
        System.out.println("Lessons Learned: " + lessonsLearned);

        System.out.println("\nCertifications:");
        System.out.println("Certification Name: " + certificationName);
        System.out.println("Certification Authority: " + certificationAuthority);
        System.out.println("Date Obtained: " + dateObtained);
        System.out.println("Certification URL: " + certificationURL);
        System.out.println("Validity Period: " + validityPeriod);
        System.out.println("Credential ID: " + credentialID);
        System.out.println("Additional Information: " + additionalInformation);
        System.out.println("Renewal Requirements: " + renewalRequirements);
        System.out.println("Renewal Deadline: " + renewalDeadline);
        System.out.println("Renewal Status: " + renewalStatus);

        System.out.println("\nLanguages:");
        System.out.println("Language Name: " + languageName);
        System.out.println("Proficiency Level: " + proficiencyLevel);
        System.out.println("Writing Proficiency: " + writingProficiency);
        System.out.println("Speaking Proficiency: " + speakingProficiency);
        System.out.println("Reading Proficiency: " + readingProficiency);
        System.out.println("Listening Proficiency: " + listeningProficiency);
        System.out.println("Certification in Language: " + languageCertification);
        System.out.println("Certification Authority: " + languageCertificationAuthority);
        System.out.println("Certification Date: " + languageCertificationDate);
        System.out.println("Certification Level: " + languageCertificationLevel);

        System.out.println("\nHobbies and Interests:");
        System.out.println("Hobby/Interest Name: " + hobbyName);
        System.out.println("Description: " + hobbyDescription);
        System.out.println("Skill Level: " + skillLevel);
        System.out.println("Time Spent Weekly: " + timeSpentWeekly);
        System.out.println("Participation in Groups/Clubs: " + participationInGroups);
        System.out.println("Achievements in Hobby/Interest: " + hobbyAchievements);
        System.out.println("Related Certifications: " + hobbyCertification);
        System.out.println("Certification Authority: " + hobbyCertificationAuthority);
        System.out.println("Certification Date: " + hobbyCertificationDate);
        System.out.println("Certification Level: " + hobbyCertificationLevel);

        System.out.println("\nReferences:");
        System.out.println("Reference Name: " + referenceName);
        System.out.println("Relationship: " + relationship);
        System.out.println("Contact Number: " + referenceContactNumber);
        System.out.println("Email Address: " + referenceEmailAddress);
        System.out.println("Company Name: " + referenceCompanyName);
        System.out.println("Position in Company: " + referencePosition);
        System.out.println("How You Know the Reference: " + howYouKnowReference);
        System.out.println("Years Known: " + yearsKnown);

        System.out.println("\nPersonal Statement:");
        System.out.println("Introduction: " + introduction);
        System.out.println("Career Objective: " + careerObjective);
        System.out.println("Strengths: " + strengths);
        System.out.println("Weaknesses: " + weaknesses);
        System.out.println("Professional Achievements: " + professionalAchievements);
        System.out.println("Career Aspirations: " + careerAspirations);
        System.out.println("Work Philosophy: " + workPhilosophy);
        System.out.println("Motivation for Career Change: " + motivationForCareerChange);
        System.out.println("Long-term Goals: " + longTermGoals);
        System.out.println("Short-term Goals: " + shortTermGoals);

        scanner.close();
    }
}
